apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: extension-fits-authn
type: helm
providerConfig:
  values:
    image:
      tag: latest
      pullPolicy: IfNotPresent
