---
name: Test Action
on:
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go 1.19
      uses: actions/setup-go@v4
      with:
        go-version: '1.19.x'

    - name: Check (lint) and Test
      run: |
        make test-in-docker
